export enum CONFIG {
  NODE_ENV = 'NODE_ENV',
  SERVER_PORT = 'SERVER_PORT',
  SERVER_HOST = 'SERVER_HOST',
  SERVER_PROTOCOL = 'SERVER_PROTOCOL',
  DB_DIALECT = 'DB_DIALECT',
  DB_STORAGE_PATH = 'DB_STORAGE_PATH',
}
